name: scrape
on:
  push:
    branches: main
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Fetch latest data
        run: Rscript scrape.R

      - uses: bcjaeger/git-auto-commit-action@v5

